### ISSUE TITLE
libdwarf-lite has no official release yet cpptrace depends on it, causing the cpptrace build to try to git clone it

### ISSUE THREAD

**Issue by marlowa** [jeremy-rifkin/libdwarf-lite#1]
cpptrace depends on libdwarf-lite but there is no official release of libdwarf-lite. This causes the cpptrace build to fetch it via git clone. This fails in corporate environments due to firewall rules. Please consider creating an official release of libdwarf-lite so that it can be built and installed independently, then the cpptrace build could be changed to refer to such a release.

**Comment by marlowa** [comment]
In the cpptrace discussion https://github.com/jeremy-rifkin/cpptrace/discussions/69 Jeremy has given instructions on how to build libdwarf-lite and cpptrace without the build trying to fetch from github. I've tried that and it works a treat. Many thanks, Jeremy. However, the instructions say to use the latest libdwarf-lite by doing a git clone. That's ok but I think it would be useful if there was an official release as well.

**Comment by jeremy-rifkin** [comment]
Hi @marlowa, I can make releases here though this repository is very much meant as a shallow mirror of https://github.com/davea42/libdwarf-code. The upstream repository is quite large due to having thousands of commits, pdf artifacts, and also code for more than just libdwarf. This repository helped substantially improve cpptrace configuration time by making the FetchContent run faster.

For your uses, it will work to either build libdwarf from this repository or upstream libdwarf-code. I can create proper documentation for the steps I outlined in the discussion and include commits / version tags to use from both libdwarf-code and this repository.

**Comment by jeremy-rifkin** [comment]
I'm closing this now as I'm taking your advice and making official release tags :)
